apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hook-log-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hook-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-hook-demo
  template:
    metadata:
      labels:
        app: nginx-hook-demo
    spec:
      terminationGracePeriodSeconds: 30
      volumes:
      - name: hook-logs
        persistentVolumeClaim:
          claimName: hook-log-pvc
      containers:
      - name: nginx
        image: nginx:alpine
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo \"<pre>PostStart hook ran at $(date)\" >> /usr/share/nginx/html/index.html"]
          preStop:
            exec:
              command: ["/bin/sh", "-c", "echo \"PreStop hook ran at $(date)</pre>\" >> /usr/share/nginx/html/index.html"]
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 5
        ports:
        - containerPort: 80
        volumeMounts:
        - name: hook-logs
          mountPath: /usr/share/nginx/html
